# Generated by Django 3.0 on 2019-12-12 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('l_number', models.IntegerField(primary_key=True, serialize=False)),
                ('l_name', models.CharField(max_length=30)),
                ('credit', models.FloatField()),
                ('time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('s_number', models.IntegerField(primary_key=True, serialize=False)),
                ('s_name', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=2)),
                ('subject', models.CharField(max_length=20)),
                ('grade', models.CharField(max_length=20)),
                ('native_place', models.CharField(max_length=30)),
                ('s_pass', models.CharField(max_length=33)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('t_number', models.IntegerField(primary_key=True, serialize=False)),
                ('t_name', models.CharField(max_length=10)),
                ('t_pass', models.CharField(max_length=33)),
                ('t_college', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(null=True)),
                ('S_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Lesson')),
                ('S_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Student')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='l_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Teacher'),
        ),
    ]
