# Generated by Django 3.0.1 on 2019-12-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('A_number', models.IntegerField(primary_key=True, serialize=False)),
                ('A_name', models.CharField(max_length=10)),
                ('A_pass', models.CharField(max_length=33)),
            ],
        ),
    ]
